Repository MemMachine/MemMachine, pull requests merged in 2025-09, with the labels that each got.

#13 Createdocs
  docs/.cursor/rules.md
  docs/README.md
  docs/api_reference/intro.mdx
  docs/api_reference/mcp/intro.mdx
  docs/api_reference/openapi.json
  docs/api_reference/python/episodic_memory.mdx
  docs/api_reference/python/episodic_memory_manager.mdx
  docs/api_reference/python/intro.mdx
  docs/api_reference/rest/intro.mdx
  docs/core_concepts/agentic_memory.mdx
  docs/core_concepts/agentic_workflow.mdx
  docs/core_concepts/index.mdx
  docs/docs.json
  docs/examples/introduction.mdx
  docs/favicon.ico
  docs/getting_started/faqs.mdx
  docs/getting_started/introduction.mdx
  docs/getting_started/quickstart.mdx
  docs/images/hero-dark.png
  docs/images/hero-light.png
  docs/images/hippo-medium.png
  docs/images/intelligent-private-memory.png
  docs/images/memmachine-overview1.png
  docs/images/memmachine-overview2.png
  docs/logo/memmachine-blue-logo-banner.png
  docs/logo/memmachine-logo-white.png
  docs/logo/memmachine-white-logo-banner.png
  docs/open_source/community.mdx
  docs/open_source/configuration.mdx
  docs/open_source/databases.mdx
  docs/open_source/embedding.mdx
  docs/open_source/features.mdx
  docs/open_source/graph.mdx
  docs/open_source/introduction.mdx
  docs/open_source/mcpserver.mdx
  docs/open_source/memory_types.mdx
  docs/open_source/pythonsdk.mdx
  docs/open_source/quickstart.mdx
  docs/open_source/reranker.mdx
  docs/open_source/restapi.mdx
  docs/profiler_engine/configuration.mdx
  docs/profiler_engine/install_guide.mdx
  docs/profiler_engine/overview.mdx
  mkdocs.yml
Labels: documentation

#20 Removed pre-commit steps
  CONTRIBUTING-CORE.md
Labels: chore

#29 Examples and QuickStart Updates
  docs/examples/introduction.mdx
  docs/getting_started/quickstart.mdx
Labels: documentation

#32 Add limit on number of episodes returned by DeclarativeMemory
  src/memmachine/episodic_memory/declarative_memory/declarative_memory.py
  src/memmachine/episodic_memory/long_term_memory/long_term_memory.py
Labels: bug, enhancement

#22 Added Ruff Workflow Action
  .github/workflows/ruff.yaml
Labels: chore

#80 Fix CrossEncoderReranker memory leak
  src/memmachine/common/reranker/cross_encoder_reranker.py
Labels: bug

#71 Create docker-image.yml
  .github/workflows/docker-image.yml
Labels: chore

#66 Create pypi-publish.yml
  .github/workflows/pypi-publish.yml
Labels: chore

#93 Updated Architecture Diagram
  assets/img/MemMachine_Architecture.png
  assets/img/MemMachine_Architecture.webp
Labels: documentation, chore

#164 Adding Installation Guide for pip and source installations.
  docs/docs.json
  docs/getting_started/install_guide.mdx
  docs/getting_started/introduction.mdx
  docs/getting_started/quickstart.mdx
Labels: documentation, enhancement

#167 0.1.2 release updates to API Reference Section
  docs/api_reference/intro.mdx
  docs/openapi.json
Labels: documentation

#176 Updating Documentation for 0.1.3 Release
  docs/api_reference/python/episodic_memory.mdx
  docs/api_reference/python/episodic_memory_manager.mdx
  docs/api_reference/python/memory_types.mdx
  docs/api_reference/python/profile_memory.mdx
  docs/getting_started/install_guide.mdx
  docs/openapi.json
Labels: documentation
